# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CadastrarUsuario',
            new_name='Usuario',
        ),
    ]
