# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('usuario', '0002_auto_20170428_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='grupo_usuario',
            field=models.ForeignKey(default=usuario.models.grupo_usuario_comum, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Tipo de Usuário'),
        ),
    ]
