# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20170502_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='', max_length=45, unique=True, verbose_name='Nome de Usuário'),
        ),
    ]
