# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rg',
        ),
    ]
