# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_usuario_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nasc',
            field=models.DateField(default='2000-01-01', verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='', max_length=1, verbose_name='Sexo'),
        ),
    ]
