# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0005_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('ambiente', models.CharField(max_length=200, verbose_name='Ambiente')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Cidade')),
                ('longitude', models.FloatField(verbose_name='Latitude')),
                ('latitude', models.FloatField(verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('problema', models.CharField(max_length=200, verbose_name='Problema')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('id_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclamacao.Ambiente', verbose_name='Ambiente')),
                ('id_cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclamacao.Cidade', verbose_name='Cidade')),
                ('id_problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclamacao.Problema', verbose_name='Problema')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=200, verbose_name='Tema')),
            ],
        ),
        migrations.AddField(
            model_name='reclamacao',
            name='id_tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclamacao.Tema', verbose_name='Tema'),
        ),
        migrations.AddField(
            model_name='reclamacao',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_usuario', to='usuario.Usuario', verbose_name='Usuário'),
        ),
    ]
