# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambiente',
            options={'verbose_name': 'Ambiente', 'verbose_name_plural': 'Ambientes'},
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='problema',
            options={'verbose_name': 'Problema', 'verbose_name_plural': 'Problemas'},
        ),
        migrations.AlterModelOptions(
            name='reclamacao',
            options={'verbose_name': 'Reclamação', 'verbose_name_plural': 'Reclamações'},
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
        migrations.RenameField(
            model_name='reclamacao',
            old_name='id_ambiente',
            new_name='ambiente',
        ),
        migrations.RenameField(
            model_name='reclamacao',
            old_name='id_cidade',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='reclamacao',
            old_name='id_problema',
            new_name='problema',
        ),
        migrations.RenameField(
            model_name='reclamacao',
            old_name='id_tema',
            new_name='tema',
        ),
        migrations.RenameField(
            model_name='reclamacao',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
