# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamacao', '0002_auto_20170504_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude'),
        ),
    ]
